# Generated by Django 3.1.3 on 2020-11-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1000)),
                ('referrer', models.CharField(max_length=1000)),
                ('serp_link', models.CharField(max_length=1000)),
                ('html', models.CharField(max_length=1000000)),
                ('start_timestamp', models.BigIntegerField()),
                ('end_timestamp', models.BigIntegerField()),
                ('dwell_time', models.IntegerField()),
                ('page_timestamps', models.CharField(max_length=1000000)),
                ('query_string', models.CharField(max_length=1000)),
                ('page_id', models.IntegerField()),
                ('mouse_moves', models.CharField(max_length=1000000)),
                ('clicked_results', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition_status', models.BooleanField(default=False)),
                ('annotation_status', models.BooleanField(default=False)),
                ('query_string', models.CharField(max_length=1000)),
                ('start_timestamp', models.IntegerField()),
                ('life_start', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timelocation', models.CharField(max_length=1000)),
                ('background', models.CharField(max_length=1000000)),
                ('intent', models.CharField(max_length=1000000)),
                ('satisfaction', models.IntegerField()),
                ('ending_type', models.IntegerField()),
                ('other_reason', models.CharField(max_length=1000)),
                ('information_difficulty', models.IntegerField()),
                ('query_difficulty', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('annotation_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.user')),
            ],
        ),
        migrations.CreateModel(
            name='SERPAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness_0', models.CharField(max_length=1000)),
                ('usefulness_1', models.CharField(max_length=1000)),
                ('usefulness_2', models.CharField(max_length=1000)),
                ('usefulness_3', models.CharField(max_length=1000)),
                ('usefulness_4', models.CharField(max_length=1000)),
                ('serp_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.pagelog')),
            ],
        ),
        migrations.CreateModel(
            name='QueryAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=1000000)),
                ('relation', models.IntegerField()),
                ('satisfaction', models.IntegerField()),
                ('ending_type', models.IntegerField()),
                ('other_reason', models.CharField(max_length=1000)),
                ('belong_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.query')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='task_annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.taskannotation'),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.user'),
        ),
        migrations.AddField(
            model_name='pagelog',
            name='belong_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.query'),
        ),
        migrations.AddField(
            model_name='pagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.user'),
        ),
    ]
